name: EpicAnchors
description: EpicAnchors
version: 1.1.2
depend: [Arconix]
softdepend: [EpicSpawners, Towny, RedProtect, Kingdoms, PlotsSquared, GriefPrevention, USkyBlock, ASkyBlock, WorldGuard, Factions, Vault]
main: com.songoda.epicanchors.EpicAnchorsPlugin
author: songoda
commands:
  EpicAnchors:
    description: I have no idea.
    default: true
    aliases: [ea]
    usage: /<command> [reload]